trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'P3 sonarcloud'
    organization: '210215-usf-revmixer'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '210215-USF-RevMixer_UploadMusic-Service'
    cliProjectName: 'UploadMusic-Service'
    cliSources: 'UploadMusicService'

- task: DotNetCoreCLI@2
  displayName: 'restore'
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: '**/*.sln'

- task: SonarCloudAnalyze@1
  displayName: run code analysis

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'